"""SQLAlchemy 2.0 ORM models for the PostgreSQL backend."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger, DateTime, ForeignKey, Index, Integer,
    JSON, String, Text,
)
from sqlalchemy import types as sa_types
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class TSVector(sa_types.TypeDecorator):
    """TSVECTOR on PostgreSQL, plain Text on every other dialect (e.g. SQLite in tests)."""
    impl = sa_types.Text
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            from sqlalchemy.dialects.postgresql import TSVECTOR
            return dialect.type_descriptor(TSVECTOR())
        return dialect.type_descriptor(sa_types.Text())


class Base(DeclarativeBase):
    pass


class PageORM(Base):
    __tablename__ = "pages"

    page_id: Mapped[str] = mapped_column(String, primary_key=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    parent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")
    status: Mapped[str] = mapped_column(String, nullable=False)
    trust_tier: Mapped[str] = mapped_column(String, nullable=False, default="unverified")
    next_approval_date: Mapped[str | None] = mapped_column(String, nullable=True)
    verified_content_hash: Mapped[str | None] = mapped_column(String, nullable=True)
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    verified_by: Mapped[str | None] = mapped_column(String, nullable=True)
    inbound_link_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_by: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    # JSON columns for data that's only read back whole (JSONB on Postgres, JSON on SQLite)
    classification: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    references: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    meta: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    # Full-text search vector — generated by Postgres, NULL on other dialects
    # The Computed() expression is Postgres-only; the Alembic migration handles it there.
    # Using TSVector type so SQLAlchemy maps to TSVECTOR on Postgres and TEXT elsewhere.
    tsv: Mapped[str | None] = mapped_column(TSVector, nullable=True)

    revisions: Mapped[list[PageRevisionORM]] = relationship(
        back_populates="page", cascade="all, delete-orphan", lazy="noload"
    )
    refs: Mapped[list[PageRefORM]] = relationship(
        foreign_keys="[PageRefORM.from_page_id]",
        back_populates="page", cascade="all, delete-orphan", lazy="noload"
    )

    __table_args__ = (
        Index("ix_pages_status", "status"),
        Index("ix_pages_trust_inbound", "trust_tier", "inbound_link_count"),
        Index(
            "ix_pages_next_approval",
            "next_approval_date",
            postgresql_where="next_approval_date IS NOT NULL",
        ),
        Index("ix_pages_tsv", "tsv", postgresql_using="gin"),
    )


class PageRevisionORM(Base):
    """Append-only page edit history (replaces embedded history array)."""
    __tablename__ = "page_revisions"

    id: Mapped[int] = mapped_column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True, autoincrement=True)
    page_id: Mapped[str] = mapped_column(
        String, ForeignKey("pages.page_id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    action: Mapped[str] = mapped_column(String, nullable=False)
    diff: Mapped[str | None] = mapped_column(Text, nullable=True)
    snapshot: Mapped[str | None] = mapped_column(Text, nullable=True)
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    page: Mapped[PageORM] = relationship(back_populates="revisions")

    __table_args__ = (
        Index("ix_page_revisions_page_id_created_at", "page_id", "created_at"),
    )


class PageRefORM(Base):
    """Normalized page references (graph edges for backlink counting)."""
    __tablename__ = "page_refs"

    id: Mapped[int] = mapped_column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True, autoincrement=True)
    from_page_id: Mapped[str] = mapped_column(
        String, ForeignKey("pages.page_id", ondelete="CASCADE"), nullable=False
    )
    ref_type: Mapped[str] = mapped_column(String, nullable=False)  # 'page' or 'file'
    to_page_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("pages.page_id", ondelete="SET NULL"), nullable=True
    )
    file_id: Mapped[str | None] = mapped_column(String, nullable=True)

    page: Mapped[PageORM] = relationship(foreign_keys=[from_page_id], back_populates="refs")

    __table_args__ = (
        Index("ix_page_refs_from", "from_page_id"),
        Index("ix_page_refs_to_page", "to_page_id"),
    )


class UserORM(Base):
    __tablename__ = "users"

    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    permission_level: Mapped[str] = mapped_column(String, nullable=False, default="read_only")
    workflow_id: Mapped[str | None] = mapped_column(String, nullable=True)
    page_permissions: Mapped[list] = mapped_column(JSON, nullable=False, default=list)


class WorkflowORM(Base):
    __tablename__ = "workflows"

    workflow_id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    steps: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    history: Mapped[list] = mapped_column(JSON, nullable=False, default=list)


class RequestORM(Base):
    __tablename__ = "requests"

    request_id: Mapped[str] = mapped_column(String, primary_key=True)
    type: Mapped[str] = mapped_column(String, nullable=False)
    page_id: Mapped[str] = mapped_column(String, nullable=False)
    requested_by: Mapped[str] = mapped_column(String, nullable=False)
    proposed_content: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    workflow_id: Mapped[str] = mapped_column(String, nullable=False)
    current_step: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending")
    history: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    __table_args__ = (
        Index("ix_requests_status", "status"),
        Index("ix_requests_requested_by", "requested_by"),
        Index("ix_requests_page_id", "page_id"),
    )


class SourceFileORM(Base):
    __tablename__ = "source_files"

    file_id: Mapped[str] = mapped_column(String, primary_key=True)
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    content_type: Mapped[str] = mapped_column(String, nullable=False, default="")
    uploaded_by: Mapped[str] = mapped_column(String, nullable=False)
    extracted_text: Mapped[str] = mapped_column(Text, nullable=False, default="")
    generated_page_ids: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
